### ISSUE TITLE
Minimize menu flash across the site when page loads

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#103]
**Bug**:Generally secondary menus (sidebar) flash open and closed when loading the page, or refreshing the page. Is there a fix to this?

**Example**
When on the Educational Campaign Materials Page, the sidebar's internal dropdown menu for that section doesn't stay open
https://www.ctoec.org/about-oec/partnerships/connecticut-head-start-state-collaboration-office/

**Comment by bloom-hondo** [comment]
This appears as two issues. 

1) The connecticut-head-start-state-collaboration-office page was added as a custom link to the menu. Because it wasn't using Wordpress' page menu item, it didn't apply the necessary selected CSS classes. Any internal ctoec.org link should use the page menu item for this.

2) The menu requires JS to display the expand / collapse behavior. If the JS fails to load for any reason (error on the page, slow internet, etc), the menu wouldn't be able to hide / show items. For this reason, it defaults to open and then closes when JS is processed.

**Comment by bloom-hondo** [comment]
@admoorgit any thoughts on the above?

**Comment by admoorgit** [comment]
1. Looks like we need to do this thing. I'm not entirely sure what the process is to achieve this. @AmeliaWellers is this something you can do?
2. Familiar with this issue from past experience. That's just part of using JS and getting it to do what we want. Considering this issue only pops if there's an, er, issue, I'm OK with it, as most users will likely not notice it.

**Comment by AmeliaWellers** [comment]
1. Good to know. I removed the custom link and re-added the menu item as a normal page, and the left sidebar stays open now. Not sure how that happened, but I know there are some other pages that may have the same situation. It's tricky to see (aka I am unable to see) the difference from the menu dashboard. 
2. I'm ok with it too! Default to open seems the most fail-safe for the future. 

Seems like this is all set then. Let me know if you see any menu items that aren't staying open this week.
