### ISSUE TITLE
How to Add a Header Image instruction page

### ISSUE THREAD

**Issue by admoorgit** [matthewcrist/ctoec#104]
Hi it's Adam I made a page detailing how to add a header image to a page.
@AmeliaWellers can you review to see if it makes sense?
@MorganGriffin-BloomWorks can you review to see if it's clear/plain language?

It's here: https://www.ctoec.org/how-to-generate-a-header-images/

This is a bad ticket.

**Comment by AmeliaWellers** [comment]
**Hi! My comments here for @admoorgit:**
- I slightly reformatted the structure of the walkthrough so that it would be easier for me to train (and also, hopefully, easier to follow) with 4 simple steps. 
- I worry slightly about someone getting overwhelmed with the number of buttons that exist in Figma, but I think the directions do a good job of being very specific about what to click. 
- I do in fact need to add my email address in order to  access any of the Figma functions... I  can see the file without logging in, but I can't do anything until I've provided my email. 

**Suggestions for additional info:**
- Ideal size and resolution of a photo, aiming for diversity, is black and white ok?, no words should be in the non-logo image... there may be others. Perhaps some of this can live in the figma file? 
- There's only one line dedicated to compressing the photo. I've added a new section where I think it makes sense to do it - Adam, would you mind elaborating a bit there about the what, why and how of compressing images?

**Comment by MorganGriffin-BloomWorks** [comment]
Hi people! 

(ADAM PLEASE IGNORE RIGHT NOW YOU BASTID)

Looks good. I made some PL type edits on the page itself and saved. Bigger thoughts:

- I think we need to frame this as an intermediate level task upfront. Just because it involves Figma, it's much more complicated than usual. Not our fault, just reality. Could say if you have familiarity with design/photo software this will be easier. Even say Odonnell can help. 
- Some stuff is just really hard to describe for a technophobic audience — e.g. resizing an image. Or the presumption that the user will know when they land on the page to hit the accordion or select an image to get the initial lefthand menu. I could see a good portion of OEC people stopping dead in their tracks when they see "run the JPG through an image compressor." Again, not a language thing, just a reality about this process.
- Gradient discussion will be confusing — explain a bit.
- I am dumb but for some reason dragging an image wasn't working as expected. Also, the open/closed eye icons. 
- A video could be good. 
- Step 4 has messed up numbering — I held off on changing because I wasn't sure how it should be arranged.

**Comment by admoorgit** [comment]
Hi!
I made some tweaks. They are:

- Fleshed out compression section
- Tweaked some language in resizing an image
- Added some language about complexity
- Fixed numbering
- added a line about the gradient layer — @MorganGriffin-BloomWorks let me know if this helps
- @AmeliaWellers re: image info — I think this will be a section within the web design guide that we'll be able to link to

Give it a look and let me know
- a.

**Comment by admoorgit** [comment]
I was able to change some things around and make it so they can output images from Powerpoint, and I can make the compression step optional, since the output is reasonable now. Will update the page to reflect this new approach!

**Comment by admoorgit** [comment]
Yay! Page has been updated: https://www.ctoec.org/how-to-generate-a-header-images/ (clearly I need to update the permalink hahaha)
@MorganGriffin-BloomWorks can you take a look when you have a chance to make sure it makes sense?

If all is well, @AmeliaWellers we'll want to move and update all the links so they point to the P drive, so it's easier for OEC to access. Right now it's all pointing to our Google Drive.

**Comment by AmeliaWellers** [comment]
Hi! I just took a scan and from first glance, this looks great. I'll work with Maggie and Chenae to add the correct links.
