### ISSUE TITLE
Homepage Issues

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#117]
A list of updates: 

### News widget
- change "See all News" to a lowercase "news". I didn't know how to change that on the homepage, it looks like it's built into the block. 

### Margins
**Issue**: Homepage sections have inconsistent page margins in tablet view
**Fix:** Have padding in other sections stay consistent with the news widget across browser dimensions and devices. 
![Screen Shot 2021-04-09 at 1.10.10 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/28c07cbb-fecb-433d-a919-3a4c24dd0fcb)

### Cosmetic
**Issue**: In Chrome/desktop devices, no blue border shows when tabbing to or clicking "See All News"
**Suggested fix**: Ensure blue border visible when tabbed through or clicked, if only for consistency purposes.

**Issue**: In Chrome/desktop devices, sections of the link's on-click blue border are covered by the grid container
![Screen Shot 2021-04-08 at 5.23.31 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/b834c034-18e8-44a9-8d13-b01544d72ab5):

**Comment by bloom-hondo** [comment]
@admoorgit this is ready for your testing.

**Comment by admoorgit** [comment]
Issue — STATUS

change "See all News" to a lowercase "news". I didn't know how to change that on the homepage, it looks like it's built into the block. **— FIXED!**

Issue: Homepage sections have inconsistent page margins in tablet view **— Would LOVE for Beth Bye's image to be either centered on the "Build Your Career" image, or right-aligned so the margin is clear. Same with the 2-1-1 logo. Otherwise, this looks great everywhere else!**

Issue: In Chrome/desktop devices, no blue border shows when tabbing to or clicking "See All News" **— It shows up, but to varying degrees of completion. Looks like either the bottom or top of the box is cut off sometimes. Also noticed it doesn't show up in the sections where I replaced the icons w/ purple variations on Live — @bloom-hondo how do we fix this?**

**Comment by AmeliaWellers** [comment]
- everything looks good!
- one new thing but should be an extremely easy fix: does it make sense for the "read the latest news" H2 to be in purple, when the other H2s are blue? Seems inconsistent to me, would like @admoorgit 's thoughts. 

Also, I only checked these updates on the latest ipad versions, chrome/safari,in browserstack, FYI.

**Comment by bloom-hondo** [comment]
This is on staging.

**Comment by admoorgit** [comment]
Can we makes em all purple like dee rest of the site? 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/72033897/117999615-06840d00-b313-11eb-91eb-e0ef7b5176f5.png">

**Comment by AmeliaWellers** [comment]
works for me if it works for Matt!
