### ISSUE TITLE
News page and filter issues 

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#118]
### Auto-format non-standard date entry 
 **Issue**: When a user types in a non-standard date format and presses "submit", they are still able to see search results within that date range.
**Fix**: When submit button is pressed, reformat any manually entered dates into DD/MM/YYYY prior to executing the filter function.  

### Add invalid date range error message
**Issue**: When user presses submit with an invalid date range or a date range that cannot be formatted, they are notified of the error. 
**Fix**: When submit button is pressed, do not trigger the filter, and show help text under the "Filter by date" fields.
**Help text**: "Please submit a valid date range"

**Comment by AmeliaWellers** [comment]
@admoorgit and I walked through a few more pieces he found on the news page, and we condensed them here. I've listed and prioritized them here. Adam, would you mind sharing an updated mockup below if you get the chance? 

### Re-add categories to ctoec.org/news items 
**Issue**: When removing the categories on the homepage (they didn't serve a purpose there), we also accidentally removed the categories on the news page (where they do serve a purpose, especially for filtering). 
**Fix:**  Please add the categories beneath each ctoec.org/news news item (thanks Adam for catching this!). 

### Add "clear filter"
**Issue**: A user cannot clear the filter without re-opening the filter tab and erasing text or deselecting categories. 
**Fix**: Add "clear filter" as clickable text underneath "filter results" tab. When a user clicks "clear filter", all filters are removed and news list is regenerated. Dropdown filter stays in (or returns to) closed position. 

### Design/Accessibility 
**Issue**: Our Work uses an H2 tag in the sidebar
**Fix**: Our Work should use an H3 tag to stay consistent across the site. 

**Issue**: News page horizontal separator does not extend to full width of news item when featured as a "NEW" post. 
**Fix**:  Extend the horizontal separator (border-bottom) to the full width

**Issue**: News Titles are bulky/large on the ctoec.org/news page
**Fix**: shrink the size of the news titles to regular link size (fx: same text size as sidebar)

### BONUS - IF LOW LIFT (aka 2-3 hrs of Matt's work or less)
- Add calendar icon to "Filter by date range" section (Adam/matt to determine exact placement)

## QA
- QA: make sure the news filter closes after pressing Search (at least on safari)

**Comment by admoorgit** [comment]
Hello! Calendar icon is already in the icon library! YAY!
Here are updated mocks, and some notes for both:

![News-Open-Filters](https://user-images.githubusercontent.com/72033897/115439626-c7afdb00-a1dc-11eb-9c50-64f9bc12c2b2.png)

- Verbiage in the buttons changed: now "Filter News", and "Show filtered results"
- Removed "news" from "results", as it was a bit redundant — is only "XX results" now
- Added calendar icon to the From and To
- Placed From and To side-by-side for this mock to see how it looked, but @AmeliaWellers mentioned it was like that at one point and didn't work well? Ok to leave stacked, or at least stack in mobile
- Changed alphabetizing of the "category" section to be down the column instead of across
**- QUESTION: I thought we split Licensing and Background Checks into 2 separate items, then deleted the original combined item (Licensing and Background Checks for Child Care and Youth Camps), but it's still in here ... @MorganGriffin-BloomWorks do you recall anything about this?**

![News-Filtered](https://user-images.githubusercontent.com/72033897/115440832-2cb80080-a1de-11eb-9608-2cdcd340bd6f.png)

- Changed verbiage of # of items so filtered lists are called "filtered results"
- Note the categories are visible on these pages — they have been stripped on live and need to be returned in this view
- Link size on the news pages should remain at it's previous size (regular <a> tag), as the slightly larger size was made to feel more substantive on the homepage — it's too clunky on internal pages
- Added "remove filters" link next to the result read-out
**- QUESTION: Should it read "remove ALL filters" or do we think "remove filters" is enough?**

**Comment by AmeliaWellers** [comment]
Let's discuss the status of this ticket at standup today and pull out only the low lift/high prio tasks for the week.

**Comment by AmeliaWellers** [comment]
These all look great and work well. The clear filter is VERY useful. Of course, I found a few edge cases that don't work within the filter: 

**Issue**: When a user adds a non-standard date format, and then fixes it, "_please add standard format MM/YY etc_." doesn't go away. 
**Fix**: When non-standard date format is standardized, also reset the alert. ![Screen Shot 2021-05-11 at 1.31.06 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/7b376fbb-89dd-4e36-a27e-1790e0196001)

**Issue**: When a user only inputs either a before date or an after date (not both), the search results do not reflect either rule. 
**Fix**: 
When a user inputs ONLY a "published before" date,  return posts that occured before that date. 
When a user inputs ONLY a "published after" date, return posts that occured after that date. 

**Issue/Fix**: I still think the "published between" should read "filter by date", both for consistency with the other two headers, and since there's already 2 instances of help text below it with the word "published" followed by a preposition. That's a minor point though.

**Comment by AmeliaWellers** [comment]
Just gave a double check for the issues above. It looks like it's working except for when I enter a publish before (only) date, it is still returning my "NEW" item from 5/11/21, which is not within the specified date range. 

I'm also posting randomly badly formatted dates into this search filter. The filter didn't catch the following dates. I am sure there are an infinite number of ways that someone could enter a badly formatted date, but flagging in case there's a quick solution at least for these: 

**This one didn't trigger the "please enter correct format" notice**
![Screen Shot 2021-05-12 at 5.20.41 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/fff14cc9-7f58-45c1-bf2b-da61e755590f)

**This one actually autocorrected to a bad format:** 
![Screen Shot 2021-05-12 at 5.21.20 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/72844212-edc0-4aa6-a9a9-10fdb845982b)
