### ISSUE TITLE
Create callout block (STAGE)

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#79]
### User Story:
As a user editing the website, I want to use a callout box to highlight different types of content on the page

### Product Requirements
- User can add a title to the callout box
- User can add body text to the callout box 
- User can choose to show an icon, or not show an icon. 
- ~User can drag a callout box above, left or right of other page content in the editor~ User can select whether callout box will have a horizontal orientation, or a card orientation
- No more than 2 vertical callout boxes can be set side by side
- User can easily locate a callout block in the block library
- the callout block icon in the block library is (!)

### Design Requirements
- All UI elements are updated according to [mockup](https://projects.invisionapp.com/boards/TG3ZKWUCF5S) (drop shadow, purple accent color, alignment, etc)
- Text color is black
- Meets accessibility requirements 
- Styling and icons are consistent for horizontal and vertical layouts
- vertical callout boxes (1 or 2 in a row) scale smoothly across multiple browser dimensions and devices

# QA Checklist 
- [x] Amelia moves QA checklist to each user story/issue 
- [x] Round 1a: Amelia tests functions and as much accessibility as possible, report findings in ticket
- [x] Round 1b: Adam tests functions and finishes accessibility checklist, report findings in ticket
- [ ] Round 2: Matt updates stage, Amelia and Adam confirm bug fixes in stage

## Product / Function
- [x]  meets product requirements
- [ ]  meets design requirements 
- [x]  meets acceptance criteria (user story) 
- [ ]  additional functions or use cases tested: 
  - [ ] 
  - [ ] 

## Accessibility
- [x] Page is keyboard accessible and free of keyboard traps
- [x] Page tab order is logical
- [x] Headings are nested properly
- [x] Frames (if applicable) are named 
- [x] CSS isn't required to use the page 
- [x] Text has sufficient color contrast
- [x] All relevant images use an “img” tag
- [x] Multimedia is tagged
~- [ ] Form instructions are associated with correct inputs~
~- [ ] Site doesn't timeout unexpectedly~
~- [ ] Default language is set~
~- [ ] Site never loses focus~
~- [ ] Page titles are descriptive~
~- [ ] Links are unique and contextual~
~- [ ] All images have alt attributes~
~- [ ] Tables are coded properly~
~- [ ] Form inputs have explicit labels~
~- [ ] Flashing elements are compliant or set to static~
~- [ ] Required plugins are linked on the page~

### Mac
- [x] OS Catalina - Safari 13, Chrome 88, 87 (Amelia)
- [x] OS Big Sur - Safari 14, Chrome 88, 87 (Adam)
### Windows 10 (Adam)
- [x] Edge 88
- [x] Safari 14, 13
- [x] Chrome 88, 87 
- [x] IE 11
### iOS (Amelia) (alternated testing in safari and chrome)
- [x] iPhone: 12, 12 Pro Max, XR, 11, 8, Mini SE
- [x] iPad 12 and Air- server wasn't responding
### Android (Adam) 
- [x] Galaxy S9

**Comment by AmeliaWellers** [comment]
## Round 1 QA
### Functionality  
- Technically the user doesn't drag the callout box, but since a user can still select vertical vs. horizontal, that's cool too! I'll update the product requirements, this is good. 
- When testing 2 in a row: 
  - the "horizontal" layout selection actually results in the "vertical" layout, and also vice versa. It seems that the words are switched.
  - the more I think about it, the more I get confused by the word choice, so others may as well. Maybe we switch to "horizontal" and "card" for maximum distinction.
- Tested the alert on the [Background checks](https://stage.ctoec.org/background-checks/) page. I know @bloom-hondo is making some updates still (toggle and drop down seem to be on their way), but wanted to see it nested with real text. Looks like there's a little extra callout box with no text on this one. 

### Design/Accessibility 
- Is it possible for the icons to display much smaller in the page editor? 
- It doesn't look like the callout boxes can be tabbed through, this should be possible
- Unsure whether we should consider the title of the callout box to be a heading?

All of the above was tested on Catalina/Chrome, will get to cross-browser testing in the afternoon

**Comment by admoorgit** [comment]
Here's the remainder of the checklist: (y = yes/good to go, n/a = not applicable to this item, "x" = incorrect, ? = question)

- [ y ]  Page is keyboard accessible and free of keyboard traps (there are no links, so there is nothing to tab to — the text is readable in VoiceOver)
- [ y ]  Page tab order is logical (again, no links)
- [ y ]  Headings are nested properly
- [ n/a ]  Frames (if applicable) are named
-  [ y ]  CSS isn't required to use the page (text is still readable and icons still appear, albeit it a little busted due to their construction)
- [ y ]  Text has sufficient color contrast
- [ ? ]  All relevant images use an “img” tag — @bloom-hondo the icons are fine because they're in an SVG tag, yeah?
- [ x ]  Multimedia is tagged – not seeing any alt text for the icons. @bloom-hondo is this something we can do via the media tab?

Findings from Browserstack coming next...

**Edge 88 on Windows 10 and Windows 7**

~~• Left horizontal purple bar not showing up on some cards ![image.png]

• Boxes that should be "cards" are showing up as "horizontal" (see previous screen shot - same in desktop and mobile)~~

*Issues were fixed, but logging here to reflect the record

-------------

No issues on Galaxy S9, Safari (Mac), or IE. Yay!

- a.

**Comment by bloom-hondo** [comment]
Because the SVGs are inline, they would need the title attribute when uploaded.

**Comment by admoorgit** [comment]
Styling adjustments for callouts based on most recent CTDS values and some custom tweaks:

Purple Bar on Horizontal + Card:
- border-left-width (or top-width on card): .375rem solid #61366F
- border-radius: .25rem;

Horizontal Margin:
- margin-bottom: .275rem;

Card Margin:
- margin-bottom: .5rem;

Shadow for both:
- box-shadow: .1rem, .25rem 1.25 rem rgba(97,54,111,.1)

SVG width and max-height:
2.5rem

@bloom-hondo is there a benefit to using PX vs. REM?
